### ISSUE TITLE
Inverting denoised version of multiple signals throws error

### ISSUE THREAD

**Issue by nsfinkelstein** [jacsor/grove#15]
Thanks for the great work on this library.

I've noticed that it's not possible to invert the denoised version of a DWT object with multiple signals.  A minimal reproducible example is below.

```
library(grove)

x = matrix(seq(64), 2)
w = grove::DWT(x)
d = grove::Denoise(w)
grove::InvDWT(d)
# Error in t(D[, , i]) %*% x : non-conformable arguments
```

Is this behavior intentional?

Thanks,
Noam

**Comment by jacsor** [comment]
Thank you for pointing out the problem. I am looking into it.

**Comment by jacsor** [comment]
Found the problem and pushed change to fix it.
